### PR TITLE
Adding example for adding a page

### PR DESCRIPTION
**Pull request by NejcZdovc**

### CODE REVIEW

**Comment by JohnBra** [comment]
Hey @NejcZdovc, thanks for contributing! I highly appreciate it!

Would you mind renaming the page to something other than "side-panel", as there is already a kind of panel in the manifest and this might be confusing.

If you could also add the steps needed to create the pages, e.g.:
1. Create new directory in pages, i.e. `src/pages/<your chosen page name>`
2. Create `src/pages/<your chosen page name>/index.tsx`, `src/pages/<your chosen page name>/index.html`, etc.etc.

I will merge it once done. Thanks again for contributing!

**Comment by NejcZdovc** [comment]
hi @JohnBra , sure I can rename it. Why I named it like this is because I was using it for that purpose: https://developer.chrome.com/docs/extensions/reference/sidePanel/. Any suggestion about what other pages chrome has that I should use?

**Comment by JohnBra** [comment]
@NejcZdovc yeah, understandable.

I think something like 'yourPage' or 'extraPage' would be good. What do you think?

**Comment by JohnBra** [comment]
@NejcZdovc still working on this?

**Pull request closed without merging**
